#!/usr/bin/env bash

REDIS_VERSION=${REDIS_VERSION:-3.2.3}

if [ ! -e redis-git ]
then
  git clone https://github.com/antirez/redis redis-git
else
  pushd redis-git
  git fetch
  popd
fi

pushd redis-git
git checkout $REDIS_VERSION
popd

make -C redis-git -j $(nproc)

gem install redis
